
# standard configuration:
runtime: python27
api_version: 1
threadsafe: yes

# Each handler redirects a set of URLs to be handled by a specific file or a script:
handlers:
- url: /stat # this will redirect all urls that start with /stat
  static_dir: sample_static_dir # it will look for the requested file in the sample_static_dir and not bother the server-side logic at all.
  login: required # we can still require login for static files, too.

- url: .* # this will redirect all URLs not handled by anything else above it.
  script: main.app # this will use the script in main.py
  login: required # before redirecting, this handler will make sure the user is logged in.

# this specifies what libraries we are using in our App Engine app:
libraries:
- name: flask
  version: "0.12"
